spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/pft_users
    username: pft
    password: pft
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
